[package]
name = "aoc"
version = "0.1.0"
authors = ["Harry Poulter <hdp1213@hotmail.com>"]
edition = "2018"
description = "Advent of Code 2020"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
